.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. planbcoin_qt test_planbcoin_qt
clean: FORCE
	$(MAKE) -C .. planbcoin_qt_clean test_planbcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_planbcoin_qt_check
planbcoin-qt planbcoin-qt.exe: FORCE
	 $(MAKE) -C .. planbcoin_qt
